version: "3.8"

services:
  demo_store:
    build:
      context: ./apps/demo_store
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - BUG_HIDE_CHECKOUT_BUTTON=false
    restart: always

  releaseguard:
    build:
      context: ./apps/releaseguard
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RELEASEGUARD_PORT=8080
    depends_on:
      - demo_store
    restart: always
