from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class EvaluationRequest(BaseModel):
    """Payload to trigger evaluation on a pull request preview."""
    repo: str
    pr_number: int
    commit_sha: str
    preview_url: str
    changed_files: List[str] = Field(default_factory=list)
    diff_text: str = ""

class EvidenceItem(BaseModel):
    """An individual piece of collected evidence or check result."""
    category: str  # e.g., "api_health", "api_checkout", "secret_scan"
    status: str    # "success", "failure", "warning"
    message: str
    risk_score: int = Field(..., ge=0, le=100)
    details: Dict[str, Any] = Field(default_factory=dict)

class GeminiJudgement(BaseModel):
    """Structured release judgement output generated by Gemini."""
    decision: str  # "APPROVE", "WARN", "BLOCK", "FIX_PR", "ESCALATE"
    risk_score: int = Field(..., ge=0, le=100)
    confidence: float = Field(..., ge=0.0, le=1.0)
    affected_journey: str
    why: str
    evidence: List[str]
    safe_next_action: str
    unsafe_actions: List[str]
    human_approval_required: bool

class ReleaseDecision(BaseModel):
    """The final release decision, including the verdict and collected evidence."""
    verdict: str  # "APPROVE" or "BLOCK"
    overall_risk: int = Field(..., ge=0, le=100)
    evidence: List[EvidenceItem]
    triggered_rules: List[str]
    markdown_report: str
    gemini_judgement: Optional[GeminiJudgement] = None
