from typing import Any, Literal

from pydantic import BaseModel, Field

PolicyDecision = Literal["APPROVE", "WARN", "BLOCK"]
GeminiDecision = Literal["APPROVE", "WARN", "BLOCK", "FIX_PR", "ESCALATE"]
ReleaseVerdict = Literal["APPROVE", "BLOCK"]


class EvaluationRequest(BaseModel):
    """Payload to trigger evaluation on a pull request preview."""

    repo: str
    pr_number: int
    commit_sha: str
    preview_url: str
    changed_files: list[str] = Field(default_factory=list)
    diff_text: str = ""


class EvidenceItem(BaseModel):
    """An individual piece of collected evidence or check result."""

    category: str  # e.g., "api_health", "api_checkout", "secret_scan"
    status: str  # "success", "failure", "warning"
    message: str
    risk_score: int = Field(..., ge=0, le=100)
    details: dict[str, Any] = Field(default_factory=dict)


class GeminiJudgement(BaseModel):
    """Structured release judgement output generated by Gemini."""

    decision: GeminiDecision
    risk_score: int = Field(..., ge=0, le=100)
    confidence: float = Field(..., ge=0.0, le=1.0)
    affected_journey: str
    why: str
    evidence: list[str]
    safe_next_action: str
    unsafe_actions: list[str]
    human_approval_required: bool
    is_fallback: bool = False


class ReleaseDecision(BaseModel):
    """The final release decision, including the verdict and collected evidence."""

    verdict: ReleaseVerdict
    overall_risk: int = Field(..., ge=0, le=100)
    evidence: list[EvidenceItem]
    triggered_rules: list[str]
    markdown_report: str
    gemini_judgement: GeminiJudgement | None = None
